### ISSUE TITLE
V3 - Rebuild

### ISSUE THREAD

**Issue by Joshua-Noakes1** [Joshua-Noakes1/Media-Activity-Bot#17]
I abandoned V2 in favour for a V3

**Comment by Joshua-Noakes1** [comment]
![image](https://user-images.githubusercontent.com/53623449/129811900-e073d5e9-a15f-46e9-9cd9-1954c83dfdb7.png)
iOS top bar doesn't look if it's left alone

**Comment by Joshua-Noakes1** [comment]
From having a quick look sharp seems to have everything that we use in jimp, compiles on oracle cloud and runs at pretty much the same speed as on my pc so we're switching to sharp

**Comment by Joshua-Noakes1** [comment]
I think with using docker the install of jimp shouldnt be an issue also sharp cant make corners correctly 
![test](https://user-images.githubusercontent.com/53623449/130275544-a5c614e4-2934-4ade-ac47-0f528904e734.png)

**Comment by Joshua-Noakes1** [comment]
jimp makes corners better
![test](https://user-images.githubusercontent.com/53623449/130282668-60a712c4-374c-4bdb-a9e1-77607825910a.png)

**Comment by Joshua-Noakes1** [comment]
![image](https://user-images.githubusercontent.com/53623449/130294381-5e6535a8-463e-4e6d-992b-a5caa65f5105.png)
Imgmin might of been the issue when saving
Left is from imgmin and right is just Jimp

**Comment by Joshua-Noakes1** [comment]
![image-d81b104e-05fe-49f6-b463-50fe1640fae5](https://user-images.githubusercontent.com/53623449/130299903-457fd20f-acf5-4ad6-8d1c-80451dea015e.png)
issue was imgmin

**Comment by Joshua-Noakes1** [comment]
![image](https://user-images.githubusercontent.com/53623449/130299924-c716def1-bebb-4ec2-bbac-5580b557bfff.png)

**Comment by Joshua-Noakes1** [comment]
![image-f7e4e53c-8d48-4393-b6c2-c21895692e14](https://user-images.githubusercontent.com/53623449/130303262-72f69a36-4402-497b-ad13-51f40f3fdd3c.png)
taglines are too long

**Comment by Joshua-Noakes1** [comment]
![Tweet1](https://user-images.githubusercontent.com/53623449/130358009-ad28814f-30ef-4f81-8591-22eeaff2cd7e.png)
tweet exists

**Comment by Joshua-Noakes1** [comment]
![test](https://user-images.githubusercontent.com/53623449/130362265-2bfda5cf-666b-47c8-b504-89e9343e5818.png)
spotify media card

**Comment by Joshua-Noakes1** [comment]
![image](https://user-images.githubusercontent.com/53623449/130366900-cf817f66-231c-409f-bb51-ce48cee9d46e.png)
Mobile image is small

**Comment by Joshua-Noakes1** [comment]
made docker image [https://github.com/Joshua-Noakes1/Ressie/pkgs/container/ressie](https://github.com/Joshua-Noakes1/Ressie/pkgs/container/ressie)

**Comment by Joshua-Noakes1** [comment]
```
/usr/src/app/node_modules/spotify-url-info/index.js:32,
        .children.filter(e => e.tagName === 'body')[0],,
^,
,
TypeError: Cannot read property 'children' of undefined,
    at /usr/src/app/node_modules/spotify-url-info/index.js:32:9,
    at processTicksAndRejections (node:internal/process/task_queues:96:5),
    at async spotify (/usr/src/app/lib/routes/spotifyRoutes/spotify.js:35:23),
```

ifttt causing issues

**Comment by Joshua-Noakes1** [comment]
ifttt had a space in the url and that caused an issue

**Comment by Joshua-Noakes1** [comment]
![image](https://user-images.githubusercontent.com/53623449/130371950-5c46c5f9-c0f8-4bfb-97fa-d05beb4711d9.png)

**Comment by Joshua-Noakes1** [comment]
![image](https://user-images.githubusercontent.com/53623449/130434800-ac02a5df-a520-49c1-83d1-276bbb213df8.png)
i might try and use regex to pull the time out of the ifttt time stamp because if youre playing lots of songs at once it gets delayed

**Comment by Joshua-Noakes1** [comment]
[https://github.com/Joshua-Noakes1/Ressie/commit/5f35fd26ddba79f56cee7d0f69c6c2f9d223d4a2](https://github.com/Joshua-Noakes1/Ressie/commit/5f35fd26ddba79f56cee7d0f69c6c2f9d223d4a2) fixes the Spotify issue

**Comment by Joshua-Noakes1** [comment]
Rewrite is done
